### ISSUE TITLE
Cannot Migrate

### ISSUE THREAD

**Issue by tommyokai** [TareqMonwer/Django-School-Management#107]
when I run `python manage.py migrate`, I get the error

```
Traceback (most recent call last):
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\environ\environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\management\commands\migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\core\checks\database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\db\utils.py", line 216, in all
    return [self[alias] for alias in self]
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\db\utils.py", line 213, in __iter__
    return iter(self.databases)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\db\utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\config\settings.py", line 173, in <module>
    'default': env.db(),
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\environ\environ.py", line 204, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "D:\Projects\Web Dev\Personal\Django Projects\Django-School-Management-master\venv\lib\site-packages\environ\environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable
```

I've been trying to fix this but it's not working
Please kindly help me out

thank you

**Comment by TareqMonwer** [comment]
Hi!
I have updated the codebase for this issue, please take a look at [this commit](https://github.com/TareqMonwer/Django-School-Management/commit/caabc0d139eb129a31d343b3fc127867d4577074)

After cloning the project, copy the `.env.example` located inside `config` folder and paste it, rename it to `.env`
This will resolve your issue.
Thanks.
