### ISSUE TITLE
ModuleNotFoundError: No module named 'celery'

### ISSUE THREAD

**Issue by phommata** [TareqMonwer/Django-School-Management#128]
I have run `pipenv install`, copied the .env.example to ./env under config directory. Installed and run redis. I have tried to install celery to resolve the error: `pip --user install celery`. ModuleNotFoundError is still occurring.

```
python manage.py migrate
Traceback (most recent call last):
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/management/base.py", line 87, in wrapped
    saved_locale = translation.get_language()
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 182, in get_language
    return _trans.get_language()
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 50, in __getattr__
    if settings.USE_I18N:
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/imparante/Documents/GitHub/Django-School-Management/config/__init__.py", line 1, in <module>
    from .celery import app as celery_app
  File "/Users/imparante/Documents/GitHub/Django-School-Management/config/celery.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/imparante/Documents/GitHub/Django-School-Management/manage.py", line 21, in <module>
    main()
  File "/Users/imparante/Documents/GitHub/Django-School-Management/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/core/management/base.py", line 386, in run_from_argv
    connections.close_all()
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/imparante/.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/imparante/Documents/GitHub/Django-School-Management/config/__init__.py", line 1, in <module>
    from .celery import app as celery_app
  File "/Users/imparante/Documents/GitHub/Django-School-Management/config/celery.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'
```

**Comment by phommata** [comment]
Ran `redis-server` and `celery -A config worker -l INFO`
