### ISSUE TITLE
Kindly help: conflict requirements.txt

### ISSUE THREAD

**Issue by thiani** [TareqMonwer/Django-School-Management#137]
Celery: I have tried giving a wider range but then I ran in to conflict - pip install "celery>4.4,<6.0"
also urllib3 and billiard
also
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Django-School-Management-1\env\lib\site-packages\django\apps\config.py", line 210, in create
    app_module = import_module(app_name)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'blog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Django-School-Management-1\manage.py", line 21, in <module>
    main()
  File "C:\Users\User\Desktop\Django-School-Management-1\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\User\Desktop\Django-School-Management-1\env\lib\site-packages\django\core\management\__init__.py", line 446, 
in execute_from_command_line
    utility.execute()
  File "C:\Users\User\Desktop\Django-School-Management-1\env\lib\site-packages\django\core\management\__init__.py", line 420, 
in execute
    django.setup()
  File "C:\Users\User\Desktop\Django-School-Management-1\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\User\Desktop\Django-School-Management-1\env\lib\site-packages\django\apps\registry.py", line 91, in populate 
    app_config = AppConfig.create(entry)
  File "C:\Users\User\Desktop\Django-School-Management-1\env\lib\site-packages\django\apps\config.py", line 212, in create    
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'blog.articles'. Check that 'articles.apps.ArticlesConfig.name' is 
correct.

I am running on windows

**Comment by mathgenius1991712** [comment]
I have the same problem when installing
I created virtualenv for this project with "python -m venv env" command
And ran "pip install -r requirements.txt"
It gave me dependencies conflicting error especially for celery thus I manually modified the version of celery in requirements.txt

**Comment by TareqMonwer** [comment]
Can you try using python 3.7 or 3.8? 
Since the project is not recently updated, it might not support latest newer Python versions.
Please let me know if it works on python 3.7 or 3.8.

**Comment by TareqMonwer** [comment]
🚀🔔 Project is now updated for latest Django & Python versions and requirements have been updated as well. 
This issue should be resolved.
