### ISSUE TITLE
error docker

### ISSUE THREAD

**Issue by alirezababae** [TareqMonwer/Django-School-Management#38]
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)

**Comment by TareqMonwer** [comment]
It's been a long time, but it's just fixed today!
