### ISSUE TITLE
Issue when migration : django.db.migrations.exceptions.NodeNotFoundError:

### ISSUE THREAD

**Issue by aksingh30** [TareqMonwer/Django-School-Management#40]
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\commands\migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\loader.py", line 274, in build_graph
    raise exc
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration course.0004_auto_20191214_2233 dependencies reference nonexistent parent node ('course', '0003_auto_20191213_1812')

**Comment by ayobabalola-git** [comment]
Have you been able to to resolve issues??
I'm facing the same issues too.

**Comment by ayobabalola-git** [comment]
I have resolved it....

navigate to course application, then to migrations and delete 0001_initial.py and 0004_auto_20191214_2233.py.

then run the following commands:

python manage.py makemigrations course
python manage.py migrate
python manage.py runserver

that's all

**Comment by TareqMonwer** [comment]
> python manage.py migrate
> Traceback (most recent call last):
> File "manage.py", line 21, in
> main()
> File "manage.py", line 17, in main
> execute_from_command_line(sys.argv)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management__init__.py", line 381, in execute_from_command_line
> utility.execute()
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management__init__.py", line 375, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
> self.execute(*args, **cmd_options)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\base.py", line 364, in execute
> output = self.handle(*args, **options)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\base.py", line 83, in wrapped
> res = handle_func(*args, **kwargs)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\core\management\commands\migrate.py", line 87, in handle
> executor = MigrationExecutor(connection, self.migration_progress_callback)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\executor.py", line 18, in **init**
> self.loader = MigrationLoader(self.connection)
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\loader.py", line 49, in **init**
> self.build_graph()
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\loader.py", line 274, in build_graph
> raise exc
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\loader.py", line 248, in build_graph
> self.graph.validate_consistency()
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\graph.py", line 195, in validate_consistency
> [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\graph.py", line 195, in
> [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
> File "D:\python-projects\django\Django-School-Management-master\env\lib\site-packages\django\db\migrations\graph.py", line 58, in raise_error
> raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
> django.db.migrations.exceptions.NodeNotFoundError: Migration course.0004_auto_20191214_2233 dependencies reference nonexistent parent node ('course', '0003_auto_20191213_1812')

Is it solved now?

**Comment by TareqMonwer** [comment]
Issue solved.
